# Generated by Django 4.1.1 on 2022-10-22 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_digital_alter_customer_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
    ]
